### ISSUE TITLE
Config-file based dns-provider

### ISSUE THREAD

**Issue by waterflier** [buckyos/buckyos#97]
Add a config-file based dns-provider, which makes it easier to run various test cases

**Comment by waterflier** [comment]
https://github.com/buckyos/buckyos/commit/c67fad500f98c0d8db93ffc6722e6e5a13c42109

Support config formal (both toml and json) look like:
```toml
["www.example.com"]
ttl = 300
A = ["192.168.1.1"]
TXT="THISISATEST"

["*.example.com"]
ttl = 300
A = ["192.168.1.2"]

["*.sub.example.com"]
ttl = 300
A = ["192.168.1.3"]

["mail.example.com"]
ttl = 300
A = ["192.168.1.106"]
```
